---
title: "TrainShootings"
author: "Mike Chirico"
date: "February 12, 2016"
output: html_document
source: https://github.com/mchirico/montcoalert/blob/master/src/r/TrainShootings.Rmd

---



```{r}
# Git Location of this file:
# https://github.com/mchirico/montcoalert/blob/master/src/r/TrainShootings.Rmd
# Load some standard libraries
suppressMessages(library(dplyr))
library(ggplot2)
library(tidyr)
library(ggmap)
library(readr)
library(lubridate)
library(reshape2)
library(animation)
library(scales)

# Grab the most recent data
urlLink="https://storage.googleapis.com/montco-stats/tzr.csv"
d=read.csv(url(urlLink),header=TRUE,stringsAsFactors=FALSE)
wd<-function(x) as.POSIXct(strptime(x, '%Y-%m-%d %H:%M:%S',tz='EST'))


# Some functions used
epoch<-function(x) strftime(x, format = "%s", tz = 'EST')
epocht<- function(x) as.integer(strtoi(x)/600)*600
epoch10<-  function(x) as.POSIXct(strptime(x, '%s',tz='EST'))
wdhr<-function(x) as.POSIXct(strptime(x, '%Y-%m-%d %H:%M:%S',tz='EST'))

# Let's add a few fields
d$mdate=wd(d$timeStamp)
d$epoch=epoch(d$timeStamp)
d$epoch10=epoch10(epocht(epoch(d$timeStamp)))

d$hr=format(d$mdate, format="%Y-%m-%d %H:00:00")
d$day=format(d$mdate, format="%Y-%m-%d 00:00:00")

# We only want data from this year
d=d[d$mdate >= '2016-01-01 00:00:00',]

# Let's get some counts. This is everything. We'll
# narrow it down in a minute
counts <- summarise(group_by(d, title), Counts=length(title))
counts <- counts[order(-counts$Counts),]
counts

# Get a subset of the data and store it as dd
tt=c('EMS: POISONING','EMS: SHOOTING','EMS: AMPUTATION','EMS: STABBING','EMS: TRAIN CRASH','Fire: TRAIN CRASH')

dd=d[d$title %in% tt,]

# Now get our subset of data
counts <- summarise(group_by(dd, title), Counts=length(title))
counts <- counts[order(-counts$Counts),]
counts

# Convert all data to csv, to view in Excel

write.csv(dd, file = "TrainShootingEtc.csv")

# Looking to map the data
map <- qmap(c(lon = -75.222372,lat = 40.156019), color="bw", fill = FALSE, add = TRUE,zoom = 11,legend = 'top')
map
# Redo the selection - You may want to add or delete
tt=c('EMS: POISONING','EMS: SHOOTING','EMS: AMPUTATION','EMS: STABBING','EMS: TRAIN CRASH')

# Resetting
dd=d[d$title %in% tt,]

# You might want to verify 
length(tt)
tt[which(tt=="EMS: POISONING")]


map +
     geom_point(data=d[d$title==tt[1],], aes(x=lng, y=lat) 
                          , alpha=1, size=4.3,col='red',
                position=position_jitter(w = 0.0009, h = 0.0009)
                ) + 
  geom_point(data=d[d$title==tt[2],], aes(x=lng, y=lat) 
                          , alpha=1, size=4.3,col='blue',
                position=position_jitter(w = 0.0009, h = 0.0009)
                ) +
  geom_point(data=d[d$title==tt[3],], aes(x=lng, y=lat) 
                          , alpha=1, size=4.3,col='green',
                position=position_jitter(w = 0.0009, h = 0.0009)
                ) +
  geom_point(data=d[d$title==tt[4],], aes(x=lng, y=lat) 
                          , alpha=1, size=4.3,col='yellow',
                position=position_jitter(w = 0.0009, h = 0.0009)
                ) +
  geom_point(data=d[d$title==tt[5],], aes(x=lng, y=lat) 
                          , alpha=1, size=4.3,col='black',
                position=position_jitter(w = 0.0009, h = 0.0009)
                )

# Look at the data by township/boro
# Just shooting and stabbing
tt=c('EMS: SHOOTING','EMS: STABBING')

# Resetting
dd=d[d$title %in% tt,]

counts <- summarise(group_by(dd,twp, title), Counts=length(title))
counts <- counts[order(-counts$Counts),]
counts

# Break it down by month
dd$month = month(dd$mdate)
dd

# Break it down by month
d$month = month(d$mdate)
d$weekdays = weekdays(d$mdate)
d$weekdays


# Add another category, and ask the question: What's the most
# dangerous township to be in, and what day of the week are
# most of the crimes?

# Break it down by wday 1=Sun,2=Mon..7=Sat
d$wday = wday(d$mdate)

tt=c('EMS: SHOOTING','EMS: STABBING','EMS: ASSAULT VICTIM')
#tt=c('EMS: STABBING')

# Resetting
dd=d[d$title %in% tt,]
dd

counts <- summarise(group_by(dd,wday,twp, title), Counts=length(title))
counts <- counts[order(-counts$Counts),]
colnames(counts) <- c("tunit","twp","title","Counts")
counts



# Playing around with displays
ggplot(data=counts, aes(x=tunit, y=Counts, group = twp, colour = title)) +
    geom_line() +
    geom_point( size=9, shape=18, fill="white") +
    facet_wrap( "twp" ) +
   ggtitle("Shootings,Stabbings,Assults\n(since beg 2016)") +
  labs(x="Weekday 1=Sun,2=Mon...4=Wed..6=Fri.",y="Counts",colour="Category") 

file='/Users/mchirico/dev/github/montcoalert/img/stabW0.png'
ggsave(file,width=480, height=240, res=120)

```



```{r}
# plot(cars)
```

